---
title: "Preservation Study for testing the efficacy of different room temperature preservation approaches"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview

This repository contains the data and RMarkdown documents used to produce publications from preservation studies conducted by the Lisa Venier and Christine Martineau groups at Natural Resources Canada Laurentian Forestry Centre, QC, Canada, and Great Lakes Forestry Centre, ON, Canada. 

# Paper and Analyses
Each paper produced from this series of experiments is saved under a different Rmarkdown file in this repository. Analyses are present within the documents as code-chunks.

- Paper 1
  + Title: Drying as an effective method to store soil samples for DNA-based microbial community analyses: a comparative study
  + Markdown: PRST soils.Rmd
  + Paper pre-print: PRST-soils.docx
  
- Paper 2 
  + Title: Desiccation as a suitable alternative to cold storage of phyllosphere samples for DNA-based microbial community analyses
  + Markdown PRST phyllospherev1.0.Rmd
  + Paper pre-print: PRST-phyllospherev1.0.docx

# Data
The source data for each paper are present in the repository in the *data* folder. 

# General analysis functions and scripts

Some generally applicable custom functions were used in these analyses, they can be found in the *src* folder.